### PR TITLE
Synchronized existing actors with changes from snactor/examples

### PR DESCRIPTION
**Pull request by artmello**

### CODE REVIEW

**Comment by bocekm** [comment]
We should probably decide what terminology we shall use. Not only for tags, but in general for Leapp. I mean, to distinguish the scenarios - upgrade/migration/containerization. If we use the term migrate in the context of containerization we may get easily confused. Maybe not now, but very like in future once we have fully fledged migration functionality (in this case I mean migration by using kickstart file).

I know that @vinzenz used the tag `migrate-machine` in the example of his PR introducing the tags but back then I really considered it just as an example.

I guess the only thing we're missing is a generic word that would describe all three things (upgrade/migration/containerization), somebody called it leappification during one Cabal :)

**Comment by examon** [comment]
@bocekm I would like to add, that we also need some naming conventions of files, tags, etc. There are instances like "check-target-output" and "set_container_directory". I think we should pick one style and stick to it.

**Comment by artmello** [comment]
Thanks, @bocekm / @examon, for reviewing this. Those were very valid points. I added a new issue (#16) to this repo about missing guideline definitions. Such document may or may not be part of the best practices effort going on right now, but I think we could formalize it and after that apply such changes to all existing actors. With that in mind, I would suggest to go on with this PR since the idea here was to just copy whatever we have at snactor's examples folder to this and do not miss anything when/if we clean up snactor's examples. Let me know what you guys think about it.

**Comment by vinzenz** [comment]
I agree with @artmello let’s do this after it was formalized

**Pull request merged**
