### PR TITLE
ci test

### PR DESCRIPTION
**Pull request by vojtechsokol**

### CODE REVIEW

**Comment by examon** [comment]
Can one of the admins verify this patch?

**Comment by vojtechsokol** [comment]
leapp-ci build

**Comment by vojtechsokol** [comment]
ok to test

**Comment by vojtechsokol** [comment]
leapp-ci build

**Comment by vojtechsokol** [comment]
retest this please

**Comment by examon** [comment]
leapp-ci build

**Comment by GAZDOWN** [comment]
leapp-ci build

**Pull request closed without merging**
