### PR TITLE
Organized actors to make this the default actors repo

### PR DESCRIPTION
**Pull request by artmello**
- Copied missing actors from snactor/examples
- Moved preupgrade report actors to a subfolder
- Moved augeas and ansible_setup to data_gathering subfolder
- Moved every other actor to containerization subfolder

### CODE REVIEW

**Comment by bocekm** [comment]
@artmello, thanks for taking on this task.
If I remember well from last week cabal we talked about having a `common` folder which would hold actors which may be utilized by any scenario (containerization/upgrades/migrations/report). It kind of corresponds to the `data_gathering` folder you have.

Then, I talked about the repo structure with @jmazanek and @pirat89 and we came up the idea that it would be more appropriate to group the actors not by scenario, but by what part of system it handles. The main reasons are:
 - we may be having one actor handling multiple scenarios, e.g. upgrades/migrations
 - if there are three actors taking care of a package - one for upgrades, second for migrations, third for report, then each of these actors would be placed in a completely different branch of the directory structure

Here's a graph to better understand what I mean.
leapp actors - page 1
You can see that the top level still distinguishes two scenarios - `upgrades` and `containerization`. We can discuss, whether it's appropriate. Maybe not, mainly because of the second bullet above. Also, we couldn't figure out a generic name that would encompass the three scenarios upgrades/migrations/report, that's why we used `upgrades` on the top level.

This is just an idea thrown for discussion.

**Comment by artmello** [comment]
@bocekm thanks for reviewing. I did change the folders names to use "common" and "upgrades", also moved actors under "upgrades" to the specific "languages" sub folders as suggested. I did not change anything under "containerization" since I am not too familiar to those actors to categorize those. Let me know what you think

**Comment by bocekm** [comment]
@artmello, thanks, it looks good for now. For future iterations, we can discuss:
- whether to merge the top level folders `upgrades` and `containerization`, it has some cons and pros.
- if we keep these two folders separated as they are, whether to keep the name `upgrades`
- whether to move the `list_content_pkg`, `list_path_content` and `verify_pkg_rhsigned` to the `common` folder as I suggested in the diagram. They seem to me quite generic and applicable to any scenario, but we let's discuss it first with the containerization guys.

**Comment by bertinatto** [comment]
This LGTM for the first iteration. I'm just wondering if we should take the chance and delete some of the unused actors we have. I'm not sure which ones can be deleted, though. @artmello, would you mind checking  with @vinzenz which ones (if any) can be removed?

@bocekm, I've a quick question for you: I like the way actors are organized in your picture, but I didn't understand how `tags` work. Do you have an example?

**Comment by artmello** [comment]
I did a couple of changes under the "containerization" folder:
- Removed actors that were clearly only used as example;
- Single actors that were not used by any other group actor were moved to "misc". Probably there are some useful actors there and also some that could be removed, but that would need another check;
- Actors that were used by multiple group actors were moved to a "common" folder;
- I tried to group the other actors by functionality (i.e. migrate-machine, target-check). In some cases there are multiple groups that will probably achieve the same thing (i.e function and function-v2) and someone could be removed, but I prefer to leave the decision to a further check;
- Redis related actors were moved to containerization/services/redis;

Please, let me know what you guys think about it

**Comment by bocekm** [comment]
@bertinatto, sorry for late response, I overlooked the email notification.
The tags - it is a future feature, already prepared by @vinzenz here https://github.com/leapp-to/snactor/pull/63/files. Based on them, snactor would pick a subset of actors and auto-generate a group actor witch such a sequence of actors that satisfies data dependencies. This is to ensure that when user wants to run just preupgrade analysis (report), just relevant actors would be executed.

**Comment by bertinatto** [comment]
Thanks, @artmello.

This LGTM, I'm wondering if we could unify those new schemas (mostly `String()` and `StringList`) with the older ones(`BaseTypeString` and `TypeStringList`). I would be OK with addressing this in a separate PR, though.

**Pull request merged**
